/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_bupt_jni_JNIMethod */

#ifndef _Included_com_bupt_jni_JNIMethod
#define _Included_com_bupt_jni_JNIMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bupt_jni_JNIMethod
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bupt_jni_JNIMethod_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
